title: <p align="center"> Lloyd Dsouza </p>
logo: /assets/img/logo.jpg

description: <p align="center">
  <br>
  I'm working on Web application development.
  Currently working in infosys.
  Interested in Data Science and Machine learning.
  Pursuing Master of Science in Machine Learning and AI.
  <br>
  </p>

theme: jekyll-theme-minimal
